# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: letsencrypt-job

bases:
  - ../../base
#- github.com/85matthew/catalog/letsencrypt-certs/base

patchesStrategicMerge:
  - patch-job-serviceaccount.yaml

#patchesJson6902:
#  - target:
#      group: batch
#      version: v1
#      kind: Job
#      name: letsencrypt-certificates-job
#      namespace: letsencrypt-job
#    path: patch-job.yaml
