# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: letsencrypt-job

bases:
- github.com/85matthew/catalog/letsencrypt-certs/base

resources:
  - sealed-cloud-dns-credentials.yaml

patchesStrategicMerge:
  - patch-job-serviceaccount.yaml

patchesJson6902:
  - target:
      kind: Job
      name: letsencrypt-certificates-job
    path: patch-job.yaml
