apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: namespace-configuration-operator

bases:
  - github.com/85matthew/catalog/namespace-configuration-operator/base

resources:
- namespace.yaml
#- operator-group.yaml
- small-ns-config.yaml
- medium-ns-config.yaml
- large-ns-config.yaml
- multitenant.yaml
- patch-default-ns-multitenant.yaml

#patchesJson6902:
#  - target:
#      group: operators.coreos.com
#      kind: Subscription
#      name: namespace-configuration-operator
#      version: v1alpha1
#    path: patch-operator-version.yaml
