apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: "2.5"
  startingCSV: kubevirt-hyperconverged-operator.v2.5.0
  config:
    env:
      - name: KVM_EMULATION
        value: "true"
    selector:
      matchLabels:
        name: hyperconverged-cluster-operator

