apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  serviceAccountIssuer: https://s3.us-east-1.amazonaws.com/napsocp2iam
