apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgCKWlqiHUE9wqJSWbXmRouFSmheTyqB0HJZDNoKCejOyK07c+uFjn4+xhfMRN4VavusiyFKNfSeT7h86A1so/xOQ7saz2MJhuCWduvdvQYdMD4I9go4rsY5BmNYz6V8Y1BFq7eK4eEi5iouxnFxDb5x9C1/9Tqsysthva/1Jmigf5UfH/UxF7LyY8n22/HO5bG96JSuO+Nwg4gCYbfdr/ckjRAn7N4xA7vi1Y+B7VJ0qSpnhdBs1WUs1oIgyxKB6bSMcMzylRAXCVhtbBoVdCPNXmqGGDlpH2h7UqMaZ2daMQU1MhBMn2+MhDQtLdpBxLh5z/47xKiqA55jkxda+l87PWNNYDb7ZfZS9sOiicPqkXg8PX7Pw1Ywf6PKwTlIMOjl30QNvtFPjGtV7Qq34acA5VROMO6ZwGia/tWWww/qy8rfzYg7zj/j3UcXmACHcGUM2IDUBKUoT95UoW9gnU463l+WO52Ye5n0BpHRwwGKmYDX4J0ezBqpS+2VYK1iW1RvbnyYaWddWTSFmSqxKqh9c/2F/lsxc0zrg2MpjjzYpKlFITQLip1pjnK4RvzqAzRqjnc9zW82r3eVxLtp9K2FF0RCvEW+T9ScY/bKzIRdO6gPUjKOfLCUX/Yn+rqWTuRH6K+TdGqQrDXIxdKc0eDVmzPK9DYv27JwgLb6niEsBFJjXtUK7AS10yH83CZTl36aCUpUa5LFcz+cyWPZpvFw4yMf7n4RcdaPa2N0s8pJYRKz1Ro/MEqfO9c7w3twXE+0tEsKDSyb/vLbA0LweQwWJw6BjZ1oxh2pjPoVK1G7UkbzWamUMX6YqS/+TP2uxoUZSMEtNvFyDLZ+617a+wV5fPT0d76JJj5sUCoIc7VViC1IeUXXLCwxeuptGCBEBmIRxVN7ddH8s6XxxDFDtoDt+LeYANx8Z/esoceC1/jMB3h+HqLlEBJC3qvkYCVurxpGr7dWxM8ZJPd9u1Aikfx3mTLZto85mxLoDOgWjGSxewqn
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
