apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: prometheus

bases:
- github.com/85matthew/catalog/grafana-operator/base/operator
- github.com/85matthew/catalog/grafana-operator/base/instance

resources:
  - namespace.yaml
  - operator-group.yaml

patchesJson6902:
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: grafana-proxy
    path: patch-proxy-namespace.yaml
