apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
spec:
  auth:
    externalIdentityProvider: false
    openShiftoAuth: true
  database:
    externalDb: false
  server:
    selfSignedCert: false
    gitSelfSignedCert: false
    tlsSupport: true
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '1'
  storage:
    pvcStrategy: 'common'
    pvcClaimSize: '1Gi'
