kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

bases:
  - github.com/85matthew/catalog/codeready-operator/base

resources:
  - namespace.yaml
  - operatorgroup.yaml
