kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-workspaces

bases:
  - github.com/85matthew/catalog/codeready-operator/base

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - checluster.yaml
