apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: openshift-operators
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  config: {}
