# Compliance Operator installation and demo scan
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - github.com/85matthew/catalog/file-integrity-operator/base

#resources:
#  - demo-scan-setting.yaml
#  - demo-scan-setting-binding.yaml
