apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpass-secret
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: a4d18613a624ada06d37
        clientSecret:
          name: github-oath-integration
        teams:
          - redhatgov/aws_infrastructure
