apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oath-integration
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCcS+ZEZWeTQHUOg3ouv0kupBWGHfHtqT6ritUtaJK0w+UMiz+OcpSosf3/lzLqmHc/3GifhLhKdLBN4BHcpYS75uG80PV4MvZtKa0hzRvpcZbUWN0yVVAhiYX5hyU9M0oq0WEA8mttfECtX/EfqQYqFfSb3FzNhie9abx+SXRo12VqjaKkSmJt4Xbf9pvD0ZdVI/ezkGus08bJ47ezl+wq3wl89Rm0SL4aVZ1PWF9JKy7Pu/RKQoVV2U6ieSCLwIxx/KZePmo6p0cFpUgWjrs8qYq5m+SJ+Sv9LYfW+jdGPoEO7pWkCWdF0a0SRIgrNLMbT9UcgqtVTaZkdm34brtrOqUR6rN3KPEocwvAimelu0KZNSOPEtM3JgLkV11ZKnQ2WIWVZ5vsTl0ZBxitvgGEajPCm6s2J/PxBdbi/wK6fm5Ox3LpzsKOU6w5c2wWADvvMyn2726v3QFVQXZdnSYKhCpOyR3RwRifoK/z2MBMTq4j45jL+XIIWzskDPQBhuy+Nldws+m8GnlAqg9/3QQxGEph0iYoMEvEIJ0d/aHAwB5dSy9l3Q56yhOjbR0dwtLb+1UO2YrhDsNGBerLAknpcm5rUqi34A9uczDaRODIJlHSiIvhzZOedb+oROv0pHOgkhWbgf2bvh52TV471BttdO8tHx9qLgYH9R4cEEE2pp1KYeuy5GPAPfWngKnaA9tGdmq5bP48vdZBZCrkVRTLrCcecxUd4dv3SFIDLNLv40c131UeZ1yE
  template:
    metadata:
      name: github-oath-integration
      namespace: openshift-config
