# Install Elasticsearch Operator.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/85matthew/catalog/cluster-logging-operator/base
#  - github.com/85matthew/catalog/installplan-approver/base

resources:
  - namespace.yaml
  - operatorgroup.yaml

#patchesStrategicMerge:
#  - patch-scansetting.yaml
