apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: prometheus

bases:
- github.com/85matthew/catalog/grafana-operator/base/operator
- github.com/85matthew/catalog/grafana-operator/base/instance

resources:
  - namespace.yaml
  - operator-group.yaml