apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Prometheus application oauth deployment
    openshift.io/display-name:  Prometheus (App Metrics)
  name: prometheus
