apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-file-integrity
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/apps/file-integrity-operator/overlays/demo
    repoURL: https://github.com/85matthew/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
