apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-security
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: acs-security
  source:
    path: manifests/apps/acs-security/base/default
    repoURL: https://github.com/85matthew/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
