apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-oath-integration
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/github-oath-integration/base
    repoURL: https://github.com/85matthew/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
